// <auto-generated />
using System;
using MTBEventProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MTBEventProject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("MTBEventProject.Models.MTBEvent", b =>
                {
                    b.Property<int>("MTBEventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("MTBEventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MTBEventDescription")
                        .HasColumnType("text");

                    b.Property<string>("MTBEventGroup")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MTBEventLocation")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MTBEventTitle")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MTBEventWebsite")
                        .HasColumnType("varchar(100)");

                    b.HasKey("MTBEventID");

                    b.ToTable("MTBEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
